name: tegonal-cv

services:

  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb-data:/data/db

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: secret1234
      MINIO_ROOT_PASSWORD: secret1234
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data

  createbucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 secret1234 secret1234;
      /usr/bin/mc mb myminio/tegonal-cv;
      exit 0;
      "

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - mailpit-data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 100
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  gotenberg:
    image: gotenberg/gotenberg:8.15
    container_name: gotenberg
    command:
      - "gotenberg"
      - "--libreoffice-auto-start=false"
      - "--libreoffice-disable-routes=true"
      - "--chromium-auto-start=true"
      - "--chromium-ignore-certificate-errors=true"
      - "--chromium-clear-cache=true"
      - "--prometheus-disable-collect=true"
      - "--webhook-disable=true"
      - "--pdfengines-disable-routes=true"
      - "--api-port=3030"
    environment:
      - "TZ=Europe/Zurich"
    ports:
      - "3030:3030"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3030/health" ]
      interval: 30s
      timeout: 20s
      retries: 3
    network_mode: "host"

  cvmanager:
    image: tegonal/cv-manager:latest
    container_name: cv-manager

volumes:
    mailpit-data:
      driver: local
    minio-data:
      driver: local
    pgadmin-data:
      driver: local
    mongodb-data:
      driver: local
