name: Build application on commit
on:
  workflow_call:
  pull_request:
  push:
    paths:
      - '**'
    branches:
      - '**'
    tags-ignore: ['*']

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24
      - name: Trying to install dependencies and build the application
        run: |
          yarn --version
          echo "Going to install dependencies..."
          yarn install
          echo "Checking version..."
          yarn next -v
          echo "Going to run checks..."
          yarn run check:ci
          echo "Going to build application..."
          yarn run build
